export const SET_SELECTED_USERS = 'SET_SELECTED_USERS';
export const SET_CHAT_USERS = 'SET_CHAT_USERS';
export const GET_CHAT_USERS = 'GET_CHAT_USERS';

export const GET_CHAT_HISTORY_REQ = 'GET_CHAT_HISTORY_REQ';
export const GET_CHAT_HISTORY_SUC = 'GET_CHAT_HISTORY_SUC';
export const GET_CHAT_HISTORY_ERR = 'GET_CHAT_HISTORY_ERR';
export const APPEND_CHAT_HISTORY = 'APPEND_CHAT_HISTORY';

export const SET_CHAT_MESSAGE = 'SET_CHAT_MESSAGE';

export const GET_CHAT_MESSAGE_REQ = 'GET_CHAT_MESSAGE_REQ';
export const GET_CHAT_MESSAGE_SUC = 'GET_CHAT_MESSAGE_SUC';
export const GET_CHAT_MESSAGE_ERR = 'GET_CHAT_MESSAGE_ERR';

export const APPEND_CHAT_MESSAGE = 'APPEND_CHAT_MESSAGE';
