export const FETCH_MICRO_APP_REQUEST = 'FETCH_MICRO_APP_REQUEST';
export const FETCH_MICRO_APP_SUCCESS = 'FETCH_MICRO_APP_SUCCESS';
export const FETCH_MICRO_APP_ERROR = 'FETCH_MICRO_APP_ERROR';

export const SET_MICRO_APP_DATA = 'SET_MICRO_APP_DATA';

export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST';
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUM_ERROR = 'FETCH_ALBUM_ERROR';

export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR';

export const SET_PLAY_DIALOG = 'SET_PLAY_DIALOG';
export const SET_MEDIA_TYPE = 'SET_MEDIA_TYPE';
export const DIALOG_STATE = {'MAXIMIZED': 0, 'MINIMIZED': 1, 'CLOSED': 2};
export const SET_START_SONG = 'SET_START_SONG';
export const SET_PLAY_MODE = 'SET_PLAY_MODE';

export const SET_FORMATTED_LIST = 'SET_FORMATTED_LIST';

export const FETCH_DB_LIST_REQ = 'FETCH_DB_LIST_REQ';
export const FETCH_DB_LIST_SUC = 'FETCH_DB_LIST_SUC';
export const FETCH_DB_LIST_ERR = 'FETCH_DB_LIST_ERR';
export const SET_DB_LIST = 'SET_DB_LIST';

export const SET_COMMENTS = 'SET_COMMENTS';
export const GET_COMMENTS_REQ = 'GET_COMMENTS_REQ';
export const GET_COMMENTS_SUC = 'GET_COMMENTS_SUC';
export const GET_COMMENTS_ERR = 'GET_COMMENTS_ERR';

export const GET_COUNTERS_REQ = 'GET_COUNTERS_REQ';
export const GET_COUNTERS_SUC = 'GET_COUNTERS_SUC';
export const GET_COUNTERS_ERR = 'GET_COUNTERS_ERR';
export const SET_COUNTERS = 'SET_COUNTERS';
